Renamed accessibility Integrated accessibility properly into quality gate

diff --git a/.github/workflows/quality-gate.yaml b/.github/workflows/quality-gate.yaml
--- a/.github/workflows/quality-gate.yaml
+++ b/.github/workflows/quality-gate.yaml
@@ -25,5 +25,9 @@ jobs:
           echo "Sonar checks failed!"
               exit 1
           fi
+          if [ "${{ needs.access.result }}" != "success" ]; then
+          echo "Sonar checks failed!"
+              exit 1
+          fi
       - name: Quality Gate Passed
         run: echo "All checks are successful. Quality Gate passed!"
